server:
    port: 4343
spring:
     mvc:
        pathmatch:
              matching-strategy: ANT_PATH_MATCHER
     datasource:
              driverClassName: com.mysql.cj.jdbc.Driver
              url: jdbc:mysql://localhost:3306/employee
              username: root
              password: root
     jpa:
        hibernate.ddl-auto: update
        show-sql: true
     application:
               name: employee_management_api